package com.deptinfo.hirbernate;

// Generated Dec 2, 2014 12:51:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * BiCopiesarticles generated by hbm2java
 */
public class BiCopiesarticles implements java.io.Serializable {

	private BiCopiesarticlesId id;
	private BiArticles biArticles;
	private String indicateurDisponible;
	private Set biEmpruntses = new HashSet(0);

	public BiCopiesarticles() {
	}

	public BiCopiesarticles(BiCopiesarticlesId id, BiArticles biArticles,
			String indicateurDisponible) {
		this.id = id;
		this.biArticles = biArticles;
		this.indicateurDisponible = indicateurDisponible;
	}

	public BiCopiesarticles(BiCopiesarticlesId id, BiArticles biArticles,
			String indicateurDisponible, Set biEmpruntses) {
		this.id = id;
		this.biArticles = biArticles;
		this.indicateurDisponible = indicateurDisponible;
		this.biEmpruntses = biEmpruntses;
	}

	public BiCopiesarticlesId getId() {
		return this.id;
	}

	public void setId(BiCopiesarticlesId id) {
		this.id = id;
	}

	public BiArticles getBiArticles() {
		return this.biArticles;
	}

	public void setBiArticles(BiArticles biArticles) {
		this.biArticles = biArticles;
	}

	public String getIndicateurDisponible() {
		return this.indicateurDisponible;
	}

	public void setIndicateurDisponible(String indicateurDisponible) {
		this.indicateurDisponible = indicateurDisponible;
	}

	public Set getBiEmpruntses() {
		return this.biEmpruntses;
	}

	public void setBiEmpruntses(Set biEmpruntses) {
		this.biEmpruntses = biEmpruntses;
	}

}
