package com.deptinfo.hirbernate;

// Generated Dec 2, 2014 12:51:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BiMembres generated by hbm2java
 */
public class BiMembres implements java.io.Serializable {

	private int noMembre;
	private BiTypesmembres biTypesmembres;
	private BiProvinces biProvinces;
	private String nom;
	private String prenom;
	private String salutation;
	private String addresse;
	private String ville;
	private String codePostal;
	private String pays;
	private String noTel;
	private String email;
	private String login;
	private String motPasse;
	private Date dernierLogin;
	private Date dateActivation;
	private int questionSecrete;
	private int reponseSecrete;
	private boolean estActif;
	private Date dateNaissance;
	private Set biEmpruntses = new HashSet(0);
	private Set biReservations = new HashSet(0);
	private Set biVenteses = new HashSet(0);

	public BiMembres() {
	}

	public BiMembres(int noMembre, BiTypesmembres biTypesmembres,
			BiProvinces biProvinces, String nom, String prenom,
			String salutation, String addresse, String ville,
			String codePostal, String pays, String noTel, String login,
			String motPasse, Date dernierLogin, Date dateActivation,
			int questionSecrete, int reponseSecrete, boolean estActif,
			Date dateNaissance) {
		this.noMembre = noMembre;
		this.biTypesmembres = biTypesmembres;
		this.biProvinces = biProvinces;
		this.nom = nom;
		this.prenom = prenom;
		this.salutation = salutation;
		this.addresse = addresse;
		this.ville = ville;
		this.codePostal = codePostal;
		this.pays = pays;
		this.noTel = noTel;
		this.login = login;
		this.motPasse = motPasse;
		this.dernierLogin = dernierLogin;
		this.dateActivation = dateActivation;
		this.questionSecrete = questionSecrete;
		this.reponseSecrete = reponseSecrete;
		this.estActif = estActif;
		this.dateNaissance = dateNaissance;
	}

	public BiMembres(int noMembre, BiTypesmembres biTypesmembres,
			BiProvinces biProvinces, String nom, String prenom,
			String salutation, String addresse, String ville,
			String codePostal, String pays, String noTel, String email,
			String login, String motPasse, Date dernierLogin,
			Date dateActivation, int questionSecrete, int reponseSecrete,
			boolean estActif, Date dateNaissance, Set biEmpruntses,
			Set biReservations, Set biVenteses) {
		this.noMembre = noMembre;
		this.biTypesmembres = biTypesmembres;
		this.biProvinces = biProvinces;
		this.nom = nom;
		this.prenom = prenom;
		this.salutation = salutation;
		this.addresse = addresse;
		this.ville = ville;
		this.codePostal = codePostal;
		this.pays = pays;
		this.noTel = noTel;
		this.email = email;
		this.login = login;
		this.motPasse = motPasse;
		this.dernierLogin = dernierLogin;
		this.dateActivation = dateActivation;
		this.questionSecrete = questionSecrete;
		this.reponseSecrete = reponseSecrete;
		this.estActif = estActif;
		this.dateNaissance = dateNaissance;
		this.biEmpruntses = biEmpruntses;
		this.biReservations = biReservations;
		this.biVenteses = biVenteses;
	}

	public int getNoMembre() {
		return this.noMembre;
	}

	public void setNoMembre(int noMembre) {
		this.noMembre = noMembre;
	}

	public BiTypesmembres getBiTypesmembres() {
		return this.biTypesmembres;
	}

	public void setBiTypesmembres(BiTypesmembres biTypesmembres) {
		this.biTypesmembres = biTypesmembres;
	}

	public BiProvinces getBiProvinces() {
		return this.biProvinces;
	}

	public void setBiProvinces(BiProvinces biProvinces) {
		this.biProvinces = biProvinces;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getAddresse() {
		return this.addresse;
	}

	public void setAddresse(String addresse) {
		this.addresse = addresse;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getNoTel() {
		return this.noTel;
	}

	public void setNoTel(String noTel) {
		this.noTel = noTel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

	public Date getDernierLogin() {
		return this.dernierLogin;
	}

	public void setDernierLogin(Date dernierLogin) {
		this.dernierLogin = dernierLogin;
	}

	public Date getDateActivation() {
		return this.dateActivation;
	}

	public void setDateActivation(Date dateActivation) {
		this.dateActivation = dateActivation;
	}

	public int getQuestionSecrete() {
		return this.questionSecrete;
	}

	public void setQuestionSecrete(int questionSecrete) {
		this.questionSecrete = questionSecrete;
	}

	public int getReponseSecrete() {
		return this.reponseSecrete;
	}

	public void setReponseSecrete(int reponseSecrete) {
		this.reponseSecrete = reponseSecrete;
	}

	public boolean isEstActif() {
		return this.estActif;
	}

	public void setEstActif(boolean estActif) {
		this.estActif = estActif;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public Set getBiEmpruntses() {
		return this.biEmpruntses;
	}

	public void setBiEmpruntses(Set biEmpruntses) {
		this.biEmpruntses = biEmpruntses;
	}

	public Set getBiReservations() {
		return this.biReservations;
	}

	public void setBiReservations(Set biReservations) {
		this.biReservations = biReservations;
	}

	public Set getBiVenteses() {
		return this.biVenteses;
	}

	public void setBiVenteses(Set biVenteses) {
		this.biVenteses = biVenteses;
	}

}
