package com.deptinfo.hirbernate;

// Generated Dec 2, 2014 12:51:27 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BiVentes generated by hbm2java
 */
public class BiVentes implements java.io.Serializable {

	private int venteId;
	private BiModespaiements biModespaiements;
	private BiMembres biMembres;
	private Date dateVente;
	private BigDecimal totalVente;
	private BigDecimal taxeProvCourante;
	private BigDecimal taxeFedCourante;
	private BigDecimal totalTaxes;
	private BigDecimal grandTotalVente;
	private Set biVentesproduitses = new HashSet(0);

	public BiVentes() {
	}

	public BiVentes(int venteId, BiModespaiements biModespaiements,
			BiMembres biMembres, Date dateVente, BigDecimal totalVente) {
		this.venteId = venteId;
		this.biModespaiements = biModespaiements;
		this.biMembres = biMembres;
		this.dateVente = dateVente;
		this.totalVente = totalVente;
	}

	public BiVentes(int venteId, BiModespaiements biModespaiements,
			BiMembres biMembres, Date dateVente, BigDecimal totalVente,
			BigDecimal taxeProvCourante, BigDecimal taxeFedCourante,
			BigDecimal totalTaxes, BigDecimal grandTotalVente,
			Set biVentesproduitses) {
		this.venteId = venteId;
		this.biModespaiements = biModespaiements;
		this.biMembres = biMembres;
		this.dateVente = dateVente;
		this.totalVente = totalVente;
		this.taxeProvCourante = taxeProvCourante;
		this.taxeFedCourante = taxeFedCourante;
		this.totalTaxes = totalTaxes;
		this.grandTotalVente = grandTotalVente;
		this.biVentesproduitses = biVentesproduitses;
	}

	public int getVenteId() {
		return this.venteId;
	}

	public void setVenteId(int venteId) {
		this.venteId = venteId;
	}

	public BiModespaiements getBiModespaiements() {
		return this.biModespaiements;
	}

	public void setBiModespaiements(BiModespaiements biModespaiements) {
		this.biModespaiements = biModespaiements;
	}

	public BiMembres getBiMembres() {
		return this.biMembres;
	}

	public void setBiMembres(BiMembres biMembres) {
		this.biMembres = biMembres;
	}

	public Date getDateVente() {
		return this.dateVente;
	}

	public void setDateVente(Date dateVente) {
		this.dateVente = dateVente;
	}

	public BigDecimal getTotalVente() {
		return this.totalVente;
	}

	public void setTotalVente(BigDecimal totalVente) {
		this.totalVente = totalVente;
	}

	public BigDecimal getTaxeProvCourante() {
		return this.taxeProvCourante;
	}

	public void setTaxeProvCourante(BigDecimal taxeProvCourante) {
		this.taxeProvCourante = taxeProvCourante;
	}

	public BigDecimal getTaxeFedCourante() {
		return this.taxeFedCourante;
	}

	public void setTaxeFedCourante(BigDecimal taxeFedCourante) {
		this.taxeFedCourante = taxeFedCourante;
	}

	public BigDecimal getTotalTaxes() {
		return this.totalTaxes;
	}

	public void setTotalTaxes(BigDecimal totalTaxes) {
		this.totalTaxes = totalTaxes;
	}

	public BigDecimal getGrandTotalVente() {
		return this.grandTotalVente;
	}

	public void setGrandTotalVente(BigDecimal grandTotalVente) {
		this.grandTotalVente = grandTotalVente;
	}

	public Set getBiVentesproduitses() {
		return this.biVentesproduitses;
	}

	public void setBiVentesproduitses(Set biVentesproduitses) {
		this.biVentesproduitses = biVentesproduitses;
	}

}
